# Generated by Django 2.2 on 2019-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpn-rest-api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
